label: "@@//benchmarking/java/com/google/j2cl/benchmarks/jre:DynamicClassDispatchRandomBenchmark_j2wasm_binary_dev"
namespace: "goog:DynamicClassDispatchRandomBenchmark_j2wasm_binary_dev.j2wasm"
suppress: "JSC_IMPLICITLY_NONNULL_JSDOC"
suppress: "JSC_UNKNOWN_EXPR_TYPE"
suppress: "JSC_ARRAY_PASSED_TO_GOOG_OBJECT"
suppress: "JSC_NESTED_NAME_IN_GOOG_MODULE"
suppress: "JSC_IMPLICITLY_NULLABLE_JSDOC"
module: "/benchmarking/java/com/google/j2cl/benchmarks/jre/DynamicClassDispatchRandomBenchmark_j2wasm_binary_dev.js"
