[project]
name = "j2cl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "notebook>=7.4.3",
    "pandas>=2.3.0",
    "seaborn>=0.13.2",
]
